/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IEntropyOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEncryptedEntropy"
      | "getFee"
      | "getRequest"
      | "isRequestFulfilled"
      | "requestEntropy"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getEncryptedEntropy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRequestFulfilled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptedEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRequestFulfilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
}

export interface IEntropyOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IEntropyOracle;
  waitForDeployment(): Promise<this>;

  interface: IEntropyOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEncryptedEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "view"
  >;

  getFee: TypedContractMethod<[], [bigint], "view">;

  getRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        consumer: string;
        tag: string;
        timestamp: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;

  isRequestFulfilled: TypedContractMethod<
    [requestId: BigNumberish],
    [boolean],
    "view"
  >;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEncryptedEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        consumer: string;
        tag: string;
        timestamp: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRequestFulfilled"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  filters: {};
}
